// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMmizaRnjLpHbM-kWZXQJWOjqu3dQDGt4',
    appId: '1:57878741939:web:80ac6f491bc9dc431c01c6',
    messagingSenderId: '57878741939',
    projectId: 'parking-system-49d7c',
    authDomain: 'parking-system-49d7c.firebaseapp.com',
    databaseURL: 'https://parking-system-49d7c-default-rtdb.firebaseio.com',
    storageBucket: 'parking-system-49d7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItG7NazOFOEd5JFdVmONOvvdhMuLsTT8',
    appId: '1:57878741939:android:e33306dc56dc02501c01c6',
    messagingSenderId: '57878741939',
    projectId: 'parking-system-49d7c',
    databaseURL: 'https://parking-system-49d7c-default-rtdb.firebaseio.com',
    storageBucket: 'parking-system-49d7c.appspot.com',
  );
}
